development:
  adapter: postgresql
  database: sudoku_dev
  username: myapp
  password: myapp
  host: localhost

test:
  adapter: postgresql
  database: sudoku_test
  username: myapp
  password: myapp
  host: localhost

production:
  adapter: postgresql
  database: sudoku_live
  username: myapp
  password: myapp
  host: localhost
